using System.Web;

namespace OdeToFood.Web.Handlers
{
    public class SampleHandler : IHttpHandler
    {
        public bool IsReusable => false;

        public void ProcessRequest(HttpContext context)
        {
            context.Response.Write("<div><p>This was generated by sample handler</p></div>");
        }
    }
}